apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: digitalocean-provisioner
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: digitalocean-provisioner
subjects:
- kind: ServiceAccount
  name: digitalocean-provisioner
